services:
  front:
    build:
      context: . 
      dockerfile: Dockerfile.nginx
    ports:
      - "3000:80" # Mapea el puerto del servidor web (nginx) al host
    networks:
      - boappnetwork

networks:
  boappnetwork:
    name: boapp_boappnetwork
